# Generated by Django 3.0.7 on 2020-06-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200624_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
